require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe BuffersController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Buffer. As you add validations to Buffer, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BuffersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all buffers as @buffers" do
      buffer = Buffer.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:buffers)).to eq([buffer])
    end
  end

  describe "GET show" do
    it "assigns the requested buffer as @buffer" do
      buffer = Buffer.create! valid_attributes
      get :show, {:id => buffer.to_param}, valid_session
      expect(assigns(:buffer)).to eq(buffer)
    end
  end

  describe "GET new" do
    it "assigns a new buffer as @buffer" do
      get :new, {}, valid_session
      expect(assigns(:buffer)).to be_a_new(Buffer)
    end
  end

  describe "GET edit" do
    it "assigns the requested buffer as @buffer" do
      buffer = Buffer.create! valid_attributes
      get :edit, {:id => buffer.to_param}, valid_session
      expect(assigns(:buffer)).to eq(buffer)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Buffer" do
        expect {
          post :create, {:buffer => valid_attributes}, valid_session
        }.to change(Buffer, :count).by(1)
      end

      it "assigns a newly created buffer as @buffer" do
        post :create, {:buffer => valid_attributes}, valid_session
        expect(assigns(:buffer)).to be_a(Buffer)
        expect(assigns(:buffer)).to be_persisted
      end

      it "redirects to the created buffer" do
        post :create, {:buffer => valid_attributes}, valid_session
        expect(response).to redirect_to(Buffer.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved buffer as @buffer" do
        post :create, {:buffer => invalid_attributes}, valid_session
        expect(assigns(:buffer)).to be_a_new(Buffer)
      end

      it "re-renders the 'new' template" do
        post :create, {:buffer => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested buffer" do
        buffer = Buffer.create! valid_attributes
        put :update, {:id => buffer.to_param, :buffer => new_attributes}, valid_session
        buffer.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested buffer as @buffer" do
        buffer = Buffer.create! valid_attributes
        put :update, {:id => buffer.to_param, :buffer => valid_attributes}, valid_session
        expect(assigns(:buffer)).to eq(buffer)
      end

      it "redirects to the buffer" do
        buffer = Buffer.create! valid_attributes
        put :update, {:id => buffer.to_param, :buffer => valid_attributes}, valid_session
        expect(response).to redirect_to(buffer)
      end
    end

    describe "with invalid params" do
      it "assigns the buffer as @buffer" do
        buffer = Buffer.create! valid_attributes
        put :update, {:id => buffer.to_param, :buffer => invalid_attributes}, valid_session
        expect(assigns(:buffer)).to eq(buffer)
      end

      it "re-renders the 'edit' template" do
        buffer = Buffer.create! valid_attributes
        put :update, {:id => buffer.to_param, :buffer => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested buffer" do
      buffer = Buffer.create! valid_attributes
      expect {
        delete :destroy, {:id => buffer.to_param}, valid_session
      }.to change(Buffer, :count).by(-1)
    end

    it "redirects to the buffers list" do
      buffer = Buffer.create! valid_attributes
      delete :destroy, {:id => buffer.to_param}, valid_session
      expect(response).to redirect_to(buffers_url)
    end
  end

end
